apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: amazon
  labels:
    app: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: jithendarramagiri1998/mini-amazon:payment-service
          ports:
            - containerPort: 3007
          env:
            - name: DATABASE_URL
              value: "postgresql://demo:demopassword@postgres.amazon.svc.cluster.local:5432/mini_amazon"
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: ORDER_SERVICE_URL
              value: "http://order-service.amazon.svc.cluster.local:3006"
            - name: PAYMENT_GATEWAY_KEY
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: gatewayKey
          readinessProbe:
            httpGet:
              path: /health
              port: 3007
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3007
            initialDelaySeconds: 8
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: amazon
spec:
  selector:
    app: payment-service
  ports:
    - port: 3007
      targetPort: 3007
      protocol: TCP
  type: ClusterIP
